### ISSUE TITLE
Firmware layout installation

### ISSUE THREAD

**Issue by ozon2** [Nuclear-Squid/ergol#35]
Hi, I'm interested in trying this layout, but I see the only installation option is to install some software to change the layout. That's not always possible, for instance on my computer at work I don't have admin rights.

I believe it would be easier to flash the layout on the keyboard so I don't have to redo the setup when I switch OS or computer. Do you have a QMK keymap? If not I could try to create it when I have some time.

**Comment by johnr14** [comment]
I was thinking the same. But it would require to do every keyboard model in the qmk repository.

Use qmk [configurator](https://config.qmk.fm).

So, we could upload our json file here and contribute  little by little. Add a qmk subdirectory in ergol project ?

The other way would be to generate .json of every keyboard in qwerty and script a parser to remap the keys. 

If I have time, I'll upload a keychron q1 map when done.

Qmk has lots of advantages, I am thinking of using caplock as a layer key and use double shifts as caplock, caps+dead would permanently switch layer and caps would revert, add insecable space (caps+space), double tap on a key for variation (like change < to ≤) without releasing altgr, altgr+space to erase, add some more unicode characters on a 4 layer?Use RGB per key light to show active layer enabled keys, light Fxx key to show layer #. 

Any other idea for qmk ? 

My rant : I don't understand that some symbols are available in a multitude of ways. Maybe it's to provide easier migration path, but I think I'll keep only one, the easier to use. Removing dups could free some space for more exotic characters that require [Unicode](https://www.alt-codes.net/).

Also I'll probably have to make stickers for my keys (as I am new to this)... Keycaps etching once finalized ?

**Comment by Nuclear-Squid** [comment]
Hi ! I’m really sorry for making you guys wait for this long for a response. I really need to check issues more often. I’ll respond separately for both comments, as I have different things to say.

For both of you : no, I don’t have a QMK keymap good to go, since most of keyboard shapes require another kind of keymap. It would be a lot of work for something that will ultimately be immediately modified. I believe it is a lot simpler for users to directly implement Ergo-L on their custom layout, though that would probably require a little guide somewhere on my end, to explain how to implement it cleanly.

For @ozon2, it’s more of a question : What system are you on ? I don’t really know the ins and outs of kalamine (the installation program I’m using), but I know there are methods to install the layout at user-space on Windows and Linux Wayland using pkl and a newly released version of kalamine respectively.

For @johnr14 I have a couple (maybe simpler things) to note :
- I know first hand that QMK Configurator is awful to reimplement Ergo-L on your keyboard (it works but it sucks). The qmk c framework is a lot simpler if you understand how it works, but the docs can be a bit intimidating when you don’t know your way around.
- The reason a lot of symbols are doubled is that some applications don’t handle keyboard shortcuts well. For instance, if you type ctrl + `-` (with `-` inputted with altgr), some applications may read that as ctrl + alt + something, instead of ctrl + `-`, so mechanical users probably want to rewrite their altgr layer using far away keys from the alpha-num layer under the hood, to prevent that problem. The other reason is that I do not f-ing want fancy Unicode characters. There are way too many, and nobody want the same. If you want weird, extra and fancy symbols, I’d advise you on building a .Xcompose file (or equivalent) on your system.

In any case, we have a dedicated [Discord server](https://discord.gg/Pkg7KvBmGQ) to talk about the development of Ergo-L, and we are getting really close to a stable release. It’s probably going to be a month away from now since we need to fix a few things at a firmware level before publishing.

Happy holidays !

**Comment by Nuclear-Squid** [comment]
I’m gonna close this issue, because [Kalamine](https://github.com/OneDeadKey/kalamine) is able to generate "mobile" drivers that you can launch without admin rights. Implementing Ergo-L using QMK is a valley of tears, made up with a surprising amount of confusing code and edge cases. I really don’t think it’s a good idea, especially since we have mobile drivers now. You can find all of the drivers [here](https://github.com/Nuclear-Squid/ergol/tree/master/0_7_0)
