### ISSUE TITLE
Document how choices were made for key positions

### ISSUE THREAD

**Issue by lobre** [Nuclear-Squid/ergol#4]
I have seen that the repository contains corpus texts that I think are used to have statistics about the French and English languages. The website also explains many global decisions about different topics.

But I think it could be valuable to go deeper in explaining how keys were positioned. Is it just "feeling" or did you use a scientific method to have the default positions of keys? What were the constraints that led you to position some keys at a specific place, and not at another? What makes you swap keys and adapt over time? Is it only by practising the layout and adjusting because of pains in the usage?

I think the field of ergonomic keyboards and layouts is really interesting, and I think that thoroughly explaining things can improve the adoption of one layout over another. Typically, those sentences found on the website are a really good start, but it would be great to have a more detailed section with the process, and with concrete examples of choices that were made for some specific keys.

```
* maximiser l’alternance des mains lors de la frappe ;
* répartir les touches de façon équitable sur les deux mains ;
* utiliser en priorité la rangée centrale, puis haute, puis inférieure ;
* en cas de non-alternance des mains sur un digramme, diriger la frappe vers le centre du clavier ce qui sollicite davantage les doigts les plus habiles à savoir l’index et le majeur.
```

And complementary point: I don't know if talks/videos exist already somewhere, but that would be great to have video matters about ErgoL.
 
Thanks a lot for the work

**Comment by lobre** [comment]
Sorry for the double post, but after having spent a large amount of time the past few days catching up with what was the current status of ergonomic keyboard layouts, there is a lot I have discovered in the process.

It seems there is a lot more information in English (around the idea of improving the typing of English), but not much progress is getting made on French keyboards, and even less in both English and French. So that’s why I particularly like your project. It seems to be a great objective to tackle!

I don’t know if you have already seen this huge and impressive document about keyboard layouts in general, but I really found that it was a gold mine (at least for me that never really got into keyboard layouts).

https://docs.google.com/document/u/0/d/1_a5Nzbkwyk1o0bvTctZrtgsee9jSP-6I0q3A0_9Mzm0/mobilebasic

I really like that they describe a process to assess the characteristics of each layout according to predefined concepts and metrics such as:

- the percentage of balance between the two hands
- the distance travelled by fingers
- the percentage of keys hit by each finger (alongside the explanation that some fingers are stronger than others)
- bigrams and trigrams and how they are composed of vowels and consonants
- same finger bigrams (sfb)
- alternations, rolls (inwards rolls, onehands, redirections)
- lateral moves of index and pinky
- information about which corpus was used (and whether punctuation and spaces are taken into account)
- ...

I wanted to reply back to this issue because those are really what I meant when I was looking for documentation of ErgoL. I understand that positioning keys to create a new layout is full of tradeoffs. I layout can be built by humans, by machines (algorithms) or a bit of both. But I feel like whatever the path, those tradeoffs should be explained so that potential users can understand if the layout suits their needs, and decide if it fits with their own constraints.

Having a technical reference explaining in detail all the steps that led to having the current layout would be super useful.

I am really stunned that this field of expertise (keyboard layouts in general) is so niche. It is a really interesting space to dig, and I feel that initiatives such as ErgoL can bring a lot, as many people type a lot on keyboards without wondering about the efficiency. Especially for French where there are way fewer options available. And I am sure that many people need to type in both English and French nowadays.

But yes, learning how to type is boring and not attractive for many :-D

**Comment by lobre** [comment]
Sorry about the monologue, please don’t feel harassed, I just document things on the go while discovering them :-) 

I have just discovered this video where you demonstrate and explain ErgoL. This is an excellent content!

https://www.videos-libr.es/w/diUCpQJABxTBT77E85EfaZ

At least it explains many of the choices that were made, and it answers many of my above questions!

So it seems you have used some corpus texts for analysis (especially for the most used letters in both languages and for bigrams) and that you use this as a steering wheel to help to make decisions. And then the rest of the process is primarily intuitions and practice, by trying things and checking if they help on a daily basis. And you also talk about concepts that I stated above, such as alternations, rolls, sfb, ...

Even after seeing the video though, I still think that having those decisions and choices written down for reference would be awesome! Maybe it could be something like:

- a main `design` document that explains how you designed the layout in the first place,
- a `changelog` file that explains each change during the lifetime of the project.

After discovering all that, I am more and more motivated to give ErgoL a try. One of the small things that I am still not really comfortable with is that the compact version (for 40%) does not have the same layer as the AltGr global one. I don’t know if it was feasible, but it would have been great to have the "lower" or "upper" layer being just the AltGr one (stripped to fit on the keyboard), but so that I can simply position the AltGr key on my Atreus keyboard and be good to go, instead of configuring the whole new layer myself!

I see that as a philosophy that resembles "mobile-first" in web development. You design first for restricted devices such as mobile browsers, and then improve the experience for larger ones such as computer screens.

For keyboard layout design, that would mean designing the layout with a 30-keys constraint in mind and then adding comfort for 50% and full keyboards by filling the empty keys so that the overall experience is improved. But the important concepts and layers would stay the same across all the variants of the layout.

**Comment by Nuclear-Squid** [comment]
Oh wow !! You really did your research ! I was about to make a long and detailed response explaining all the design patterns I used, main goals... but you seem to have hit the nail on the head (you even got the little nuances of what is a good bigram, I'm honestly impressed) !

Since I don't have a lot more to say, I'll take the time I have to address a few points : 

- There is in fact not a lot of documentation regarding French keyboard ergonomics. Azerty is (in my eyes) a straight downgrade from qwerty, due to placing some letters further away than before (like `a` and `m`), and Bépo, while an improvement in French typing still falls in a lot of the same traps as azerty (like shift to get numbers, or big extensions to get some letters). There's also dvorak-fr who.... exist....? So yeah, the fact there is not a lot for French typist, and nothing for fr/en typists was my main motivator for Ergo-L.
- I didn't document my changes much throughout my experiments, but I'll try to write a retrospect when I have a bit of time. I'll surely miss a few things here and there, but I could get the most important parts.
- I'm not sure if there is enough room for both numbers + shift numbers _and_ programming symbols on the same layer. The current Alt-gr has everything except shift + num and we already have to place symbols on the number row, so it's not compatible with 40% keebs. I'm currently experimenting with a new Alt-gr layer, but it focuses solely on programming symbols. It would be the same layer even for 36-keys keebs, but you'll need a separate layer for numbers.
- I'm experimenting with some changes that try to fix the dreaded `unc`, and they look promising. It's still a bit vague, but definitely goes in the right direction.
- There's a [Discord server](https://discord.gg/yDEWj6VtKn) now ! You were the second person to independently say I should create a hub so that we could discuss the layout, so I made it yesterday. Right now it's a bit bare-bones, since there really isn't a lot of people, but I'll expand it if it needs to :)

**Comment by lobre** [comment]
> Oh wow !! You really did your research ! I was about to make a long and detailed response explaining all the design patterns I used, main goals... but you seem to have hit the nail on the head (you even got the little nuances of what is a good bigram, I'm honestly impressed) !

Thank you for the compliment! When I catch interest in a domain such as this one, I can really go down the rabbit hole and lose myself reading a looot of doc ^^.

> I didn't document my changes much throughout my experiments, but I'll try to write a retrospect when I have a bit of time. I'll surely miss a few things here and there, but I could get the most important parts.

That would be awesome!

> I'm currently experimenting with a new Alt-gr layer, but it focuses solely on programming symbols. It would be the same layer even for 36-keys keebs, but you'll need a separate layer for numbers.

I will also experiment with that, I might have a few ideas as well.

And that is cool that you created a Discord server, I’ll join it. I think it will be easier to interact and avoid those long posts that are not even real "issues".
