### ISSUE TITLE
Hard to type the HE bigram

### ISSUE THREAD

**Issue by lobre** [Nuclear-Squid/ergol#5]
As reported per the blog post on [WorkmanLayout](https://workmanlayout.org/), Colemak makes it hard to type the bigram `HE`, which is the second most frequent bigram in the English language. Here is an extract:

> Just ask yourself, how often do you type ‘the’, ‘these’, ‘them’, ‘when’, and ‘where’, etc. on a day-to-day basis? It’s even worse when you’re typing these words in the beginning of a sentence. Try typing “The” with the T capitalized on Colemak and hopefully you’ll see what I mean. Your right hand will move somewhat like this: you swing to the right to get the SHIFT key with your pinky, then you swing back to the left to get the letter ‘H’, and then you move to the right again to get the letter ‘E’. All this is happening in a split second. That’s quite a bit of lateral movement.

I can see that ErgoL reproduces the same thing.

I am not sure how, but maybe this should be avoided. Generally speaking, I feel that taking bigrams and trigrams into account (for both English and French) is an important constraint to having an ergonomic layout polyvalent for those languages.

What do you think?

**Comment by Nuclear-Squid** [comment]
Hi ! `HE` being typed similarly to colemack is a somewhat frequent complaint people have with the layout. About half of the people I've asked don't like it, and the other half doesn't mind, which means this bigram is less than ideal and could be improved to make it more comfortable / efficient. Here's why I didn't do it :

One thing to note, is that while the `H` is really frequent, (the fifth most frequent letter in English), the subset of letters it chains into is very slim, much more than most other letters in English. (It's basically `[tcwsg]h[aeiot]`, and of those letters, only `eoi` are on the same hand as `h`. So the approached I had was that I could ignore all of the letters on the opposite hand, since those bigrams will always be comfortable, and just make sure that the few rolls I have to take into account work, (which isn't that much of a success when it comes to `he`). So all in all, could be better, but it's not too bad...

I tried to make it a bit more comfortable in English, but I quickly got stuck. You see, the only way (that I could find at least) to improve `he` was to place it on the qwerty [D ] key, which is what Workman did. The main problem with this approach is that `h` is just not relevant enough in French to be on such an important space. It's the 17th most frequent letter in the alphabet, 20th if you count accents and punctuation, and it's combos are *even more* niche than in English (where it's just `ch[eoa]`). Optimizing the `h` for English would certainly be a slight improvement, but it would completely break the French side of the layout.

Now it's not to say that it's unsolvable, it's just that I didn't find a way of fixing this bigram without creating a lot more problems. You could try to switch a few letters around and see what happens, I'm open for suggestions ! One thing I tried but am currently not sure if it changes anything was to swap `K` and `H`, so that it is a row lower. In my eyes `he` feels a tad more comfortable on my laptop's keyboard and on my x-bows (an ortholinear keeb with a slight angle between both hands), but not on my Iris (a split ortholinear), so I'd like a second opinion on that.

**Comment by lobre** [comment]
Let me sum it up to make sure I understood correctly!

So taking all the letters of the alphabet, only the 5 letters `a`, `e`, `i`, `o`, and `t` are considered as frequently typed just after `h` (both in French and English). So for `a` and `t`, it is not a problem because we have hands alternation, and for `e`, `i` and `o`, it is "not that bad" because `he`, `hi` and `ho` do roll sufficiently well-enough.

Maybe it could be interesting to study trigrams to check if the frequent ones starting with `he`, `hi` or `ho` are comfortable (like checking if they result in "redirections" or "pinball" effects instead of pure inward/outward rolls).

I don’t remember from the video, but I think you said you took mostly bigrams into account, but not, especially trigrams, am I right?

Another point of view could be what Colemak DH has done (a mod that was created over Colemak to mitigate a few problems). By the way, this version seems to become more popular than the default one nowadays (from what I read). They swapped `h` with `m`. But in ErgoL, we have the dead key at that position so it does not work.

I can try a few positions but I am not sure I will come up with a better solution than yours ^^. And about your try that swaps `h` and `k`, I am not sure it is a good option either. On my Atreus, the `k` is even less comfortable to reach than `h`. The extension of the index is farther than for the `h`. `j` would become simpler to reach for vim, however, but this would also break the mirroring of `j` and `k`.

Thanks again for taking the time to answer my question. It is really appreciated and it’s a joy to try to understand the decisions you made while creating this layout!
